version: 2
jobs:
  build:
    docker:
      - image: rocker/tidyverse

    steps:
      - checkout

      - run:
          name: Install packages
          command: |
             R -q -e "install.packages(c('rmarkdown'))" 
      - run:
          name: Build site
          command: |
             R -q -e "rmarkdown::render('index.Rmd',output_file='index.html')"
            
workflows:
    version: 2
    weekly:
        jobs:
            - build
        triggers:
            - schedule:
                cron: 0 3 * * *
                filters:
                    branches:
                        only:
                            - master
