version: 2
jobs:
  join-and-publish:
    docker:
      - image: colinfay/r-ci-tidyverse:3.6.0
      
    steps:
      - checkout
      - run:
          name: All
          command: |
            R -e "rmarkdown::render('index.Rmd',output_file='index.html')"
            
  update-and-publish:
    docker:
      - image:  circleci/python:3.6
      
    steps: 
      - checkout
      - run:
          name: Get the data
          command: |
            ./getdata.sh
      - run:
          name: Publish on data.gouv
          command: |
            ./upload.sh

workflows:
    version: 2
    daily:
        jobs:
            - join-and-publish
        triggers:
            - schedule:
                cron: 0 3 * * *
                filters:
                    branches:
                        only:
                            - master
